# Docker Compose to run app + PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-01
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    env_file: .env
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
